package funkin.visualscripting;

import funkin.visualscripting.nodes.*;
import haxe.ds.StringMap;

/**
 * FEATURE 78: Visual Script Compiler
 * 
 * Compiles a VisualScriptGraph into HScript code that can be
 * executed by the engine's HScript interpreter.
 */
class VSCompiler {
	var graph:VisualScriptGraph;
	var output:StringBuf;
	var indent:Int = 0;
	var varCounter:Int = 0;
	var functions:StringBuf;
	var mainBody:StringBuf;
	var importedClasses:Map<String, Bool> = [];
	
	// Node compilation cache to avoid duplicate compilation
	var compiledNodes:Map<String, String> = [];
	
	public function new(graph:VisualScriptGraph) {
		this.graph = graph;
	}
	
	/**
	 * Compile the graph to HScript code
	 */
	public function compile():String {
		output = new StringBuf();
		functions = new StringBuf();
		mainBody = new StringBuf();
		compiledNodes = [];
		varCounter = 0;
		
		// Header comment
		addLine('// Auto-generated by Visual Script Compiler');
		addLine('// Graph: ${graph.name} v${graph.version}');
		addLine('// Author: ${graph.author}');
		addLine('');
		
		// Variable declarations
		for (name => varData in graph.variables) {
			addLine('var $name = ${valueToString(varData.defaultValue)};');
		}
		if (graph.variables.keys().hasNext()) addLine('');
		
		// Compile event handler nodes
		var eventNodes = graph.getNodesByType(VSOnEventNode);
		for (node in eventNodes) {
			compileEventHandler(node);
		}
		
		// Compile function nodes
		var funcNodes = graph.getNodesByType(VSFunctionDefNode);
		for (node in funcNodes) {
			compileFunction(node);
		}
		
		// Compile entry point nodes
		var entryNodes = findEntryNodes();
		for (node in entryNodes) {
			if (!Std.isOfType(node, VSOnEventNode) && !Std.isOfType(node, VSFunctionDefNode)) {
				compileExecutionChain(node, mainBody);
			}
		}
		
		// Assemble final output
		output.add(functions.toString());
		output.add(mainBody.toString());
		
		return output.toString();
	}
	
	/**
	 * Find nodes that serve as execution entry points
	 */
	function findEntryNodes():Array<VSNode> {
		var connectedInputs:Map<String, Bool> = [];
		for (conn in graph.connections) {
			if (conn.targetPort == "exec_in") {
				connectedInputs.set(conn.targetNodeID, true);
			}
		}
		
		return graph.nodes.filter(n -> {
			return n.hasExecutionInput && !connectedInputs.exists(n.id) && n.isEnabled;
		});
	}
	
	/**
	 * Compile an event handler node into a function
	 */
	function compileEventHandler(node:VSOnEventNode):Void {
		var funcName = 'on_${node.eventName}';
		
		addFunctionLine('function $funcName() {');
		indent++;
		
		compileExecutionChain(node, functions, true);
		
		indent--;
		addFunctionLine('}');
		addFunctionLine('');
	}
	
	/**
	 * Compile a function definition node
	 */
	function compileFunction(node:VSFunctionDefNode):Void {
		var funcName = node.functionName;
		var params = node.parameters.map(p -> p.name).join(', ');
		
		addFunctionLine('function $funcName($params) {');
		indent++;
		
		compileExecutionChain(node, functions, true);
		
		indent--;
		addFunctionLine('}');
		addFunctionLine('');
	}
	
	/**
	 * Compile an execution chain starting from a node
	 */
	function compileExecutionChain(startNode:VSNode, buf:StringBuf, isFunction:Bool = false):Void {
		var visited:Map<String, Bool> = [];
		var currentNode:VSNode = startNode;
		
		while (currentNode != null && !visited.exists(currentNode.id)) {
			visited.set(currentNode.id, true);
			
			var code = compileNode(currentNode);
			if (code != null && code.length > 0) {
				for (line in code) {
					buf.add(indentString());
					buf.add(line);
					buf.add('\n');
				}
			}
			
			// Follow execution output
			if (currentNode.hasExecutionOutput) {
				var connections = graph.getConnectionsFrom(currentNode.id, "exec_out");
				if (connections.length > 0) {
					currentNode = graph.nodeMap.get(connections[0].targetNodeID);
				} else {
					currentNode = null;
				}
			} else {
				currentNode = null;
			}
		}
	}
	
	/**
	 * Compile a single node to HScript code lines
	 */
	function compileNode(node:VSNode):Array<String> {
		if (compiledNodes.exists(node.id)) {
			return compiledNodes.get(node.id).split('\n').filter(l -> l.length > 0);
		}
		
		var lines:Array<String> = [];
		
		// Add comment if present
		if (node.comment != null && node.comment.length > 0) {
			lines.push('// ${node.comment}');
		}
		
		// Node-specific compilation
		if (Std.isOfType(node, VSSetVariableNode)) {
			var n = cast(node, VSSetVariableNode);
			var valExpr = compileInputExpression(node, "value");
			lines.push('${n.variableName} = $valExpr;');
		}
		else if (Std.isOfType(node, VSGetVariableNode)) {
			// Pure data node, no execution code
		}
		else if (Std.isOfType(node, VSMathNode)) {
			var n = cast(node, VSMathNode);
			var a = compileInputExpression(node, "a");
			var b = compileInputExpression(node, "b");
			var op = n.operation;
			var tempVar = '_vsc_${varCounter++}';
			lines.push('var $tempVar = ($a) $op ($b);');
			node.outputValues.set("result", tempVar);
		}
		else if (Std.isOfType(node, VSIfNode)) {
			var condition = compileInputExpression(node, "condition");
			lines.push('if ($condition) {');
			// True branch and false branch would be compiled separately
			lines.push('}');
		}
		else if (Std.isOfType(node, VSForLoopNode)) {
			var from = compileInputExpression(node, "from");
			var to = compileInputExpression(node, "to");
			var step = compileInputExpression(node, "step");
			var varName = cast(node, VSForLoopNode).indexVariable;
			lines.push('for ($varName in $from...$to) {');
			lines.push('}');
		}
		else if (Std.isOfType(node, VSWhileLoopNode)) {
			var condition = compileInputExpression(node, "condition");
			lines.push('while ($condition) {');
			lines.push('}');
		}
		else if (Std.isOfType(node, VSCallFunctionNode)) {
			var n = cast(node, VSCallFunctionNode);
			var args = n.argumentNames.map(a -> compileInputExpression(node, a)).join(', ');
			lines.push('${n.functionName}($args);');
		}
		else if (Std.isOfType(node, VSPlaySoundNode)) {
			var path = compileInputExpression(node, "path");
			var volume = compileInputExpression(node, "volume");
			lines.push('FlxG.sound.play(Paths.sound($path), $volume);');
		}
		else if (Std.isOfType(node, VSSetPropertyNode)) {
			var obj = compileInputExpression(node, "object");
			var prop = cast(node, VSSetPropertyNode).propertyName;
			var val = compileInputExpression(node, "value");
			lines.push('$obj.$prop = $val;');
		}
		else if (Std.isOfType(node, VSGetSpriteNode)) {
			var name = compileInputExpression(node, "name");
			lines.push('// getSprite: $name');
		}
		else if (Std.isOfType(node, VSTweenNode)) {
			var target = compileInputExpression(node, "target");
			var duration = compileInputExpression(node, "duration");
			var props = compileInputExpression(node, "properties");
			lines.push('FlxTween.tween($target, {$props}, $duration);');
		}
		else if (Std.isOfType(node, VSSpawnSpriteNode)) {
			var imgPath = compileInputExpression(node, "imagePath");
			var x = compileInputExpression(node, "x");
			var y = compileInputExpression(node, "y");
			var varName = '_spr_${varCounter++}';
			lines.push('var $varName = new FunkinSprite($x, $y);');
			lines.push('$varName.loadGraphic(Paths.image($imgPath));');
			lines.push('add($varName);');
		}
		else if (Std.isOfType(node, VSCameraShakeNode)) {
			var intensity = compileInputExpression(node, "intensity");
			var duration = compileInputExpression(node, "duration");
			lines.push('camGame.shake($intensity, $duration);');
		}
		else if (Std.isOfType(node, VSCameraFlashNode)) {
			var color = compileInputExpression(node, "color");
			var duration = compileInputExpression(node, "duration");
			lines.push('camGame.flash($color, $duration);');
		}
		else if (Std.isOfType(node, VSLogNode)) {
			var msg = compileInputExpression(node, "message");
			lines.push('trace($msg);');
		}
		else if (Std.isOfType(node, VSReturnNode)) {
			var val = compileInputExpression(node, "value");
			lines.push('return $val;');
		}
		else if (Std.isOfType(node, VSStringConcatNode)) {
			var a = compileInputExpression(node, "a");
			var b = compileInputExpression(node, "b");
			var tempVar = '_vsc_${varCounter++}';
			lines.push('var $tempVar = Std.string($a) + Std.string($b);');
		}
		else if (Std.isOfType(node, VSCompareNode)) {
			var n = cast(node, VSCompareNode);
			var a = compileInputExpression(node, "a");
			var b = compileInputExpression(node, "b");
			var tempVar = '_vsc_${varCounter++}';
			lines.push('var $tempVar = ($a) ${n.comparison} ($b);');
		}
		else {
			// Generic node: generate a comment
			lines.push('// Node: ${node.displayName} (${node.id})');
		}
		
		compiledNodes.set(node.id, lines.join('\n'));
		return lines;
	}
	
	/**
	 * Compile an input port to an expression string
	 */
	function compileInputExpression(node:VSNode, portName:String):String {
		var conn = graph.getConnectionTo(node.id, portName);
		if (conn != null) {
			var sourceNode = graph.nodeMap.get(conn.sourceNodeID);
			if (sourceNode != null) {
				return compileOutputExpression(sourceNode, conn.sourcePort);
			}
		}
		
		var port = node.getInputPort(portName);
		return port != null ? valueToString(port.defaultValue) : "null";
	}
	
	/**
	 * Compile an output port to an expression string
	 */
	function compileOutputExpression(node:VSNode, portName:String):String {
		if (Std.isOfType(node, VSGetVariableNode)) {
			return cast(node, VSGetVariableNode).variableName;
		}
		if (Std.isOfType(node, VSMathNode)) {
			var n = cast(node, VSMathNode);
			var a = compileInputExpression(node, "a");
			var b = compileInputExpression(node, "b");
			return '($a ${n.operation} $b)';
		}
		if (Std.isOfType(node, VSCompareNode)) {
			var n = cast(node, VSCompareNode);
			var a = compileInputExpression(node, "a");
			var b = compileInputExpression(node, "b");
			return '($a ${n.comparison} $b)';
		}
		if (Std.isOfType(node, VSStringConcatNode)) {
			var a = compileInputExpression(node, "a");
			var b = compileInputExpression(node, "b");
			return '(Std.string($a) + Std.string($b))';
		}
		if (Std.isOfType(node, VSConstantNode)) {
			return valueToString(cast(node, VSConstantNode).value);
		}
		if (Std.isOfType(node, VSGetPropertyNode)) {
			var obj = compileInputExpression(node, "object");
			var prop = cast(node, VSGetPropertyNode).propertyName;
			return '$obj.$prop';
		}
		if (Std.isOfType(node, VSCallFunctionNode)) {
			var n = cast(node, VSCallFunctionNode);
			var args = n.argumentNames.map(a -> compileInputExpression(node, a)).join(', ');
			return '${n.functionName}($args)';
		}
		if (Std.isOfType(node, VSGetSpriteNode)) {
			var name = compileInputExpression(node, "name");
			return 'getSprite($name)';
		}
		if (Std.isOfType(node, VSNegateNode)) {
			var val = compileInputExpression(node, "value");
			return '!($val)';
		}
		if (Std.isOfType(node, VSArrayNode)) {
			var items = cast(node, VSArrayNode).itemPorts.map(p -> compileInputExpression(node, p)).join(', ');
			return '[$items]';
		}
		if (Std.isOfType(node, VSArrayAccessNode)) {
			var arr = compileInputExpression(node, "array");
			var idx = compileInputExpression(node, "index");
			return '$arr[$idx]';
		}
		
		// Fallback: use cached temp variable
		if (node.outputValues.exists(portName)) {
			return Std.string(node.outputValues.get(portName));
		}
		
		return "null";
	}
	
	/**
	 * Convert a value to its HScript string representation
	 */
	function valueToString(value:Dynamic):String {
		if (value == null) return "null";
		if (Std.isOfType(value, String)) return '"${Std.string(value).replace("\\", "\\\\").replace("\"", "\\\"")}"';
		if (Std.isOfType(value, Bool)) return Std.string(value);
		if (Std.isOfType(value, Int) || Std.isOfType(value, Float)) return Std.string(value);
		if (Std.isOfType(value, Array)) {
			var arr:Array<Dynamic> = cast value;
			return '[${arr.map(v -> valueToString(v)).join(", ")}]';
		}
		return Std.string(value);
	}
	
	function addLine(line:String):Void {
		output.add(indentString());
		output.add(line);
		output.add('\n');
	}
	
	function addFunctionLine(line:String):Void {
		functions.add(indentString());
		functions.add(line);
		functions.add('\n');
	}
	
	function indentString():String {
		return StringTools.lpad("", "\t", indent);
	}
}
